name: test
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        test-name: [
          test-kitsune-p2p,
          test-holochain,
        ]
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          '1.75.0',
        ]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: go toolchain
        uses: actions/setup-go@v5
        with:
          go-version: '=1.20.0'

      - name: rust toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - name: install vcpkg packages
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: libsodium
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true

      - name: test windows
        if: matrix.os == 'windows-latest'
        run: |-
          $env:SODIUM_LIB_DIR="$(pwd)\vcpkg\packages\libsodium_x64-windows-release\lib"
          make ${{ matrix.test-name }}

      - name: test
        if: matrix.os != 'windows-latest'
        run: make ${{ matrix.test-name }}
